######################## default configuration ####################

theme ="cusine-menu-hugo"
defaultContentLanguage = 'zh'
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45

baseURL = "/" 


[languages]
############################## ZH config ###############################
    [languages.zh]
        languageName = '中文'
        title='黑客茶舖'
        contentDir = "content/zh"

# subtitles
[languages.zh.params.cuisine]
food = "台菜"
pasta = "義大利麵"
drink ="茶"
coffee="咖啡"

# subtitles
[languages.zh.params.event]
heading="活動"
heading2 ="店內菜單"
############################## navigation zh ###############################
        [[languages.zh.menu.main]]
        name = "首頁"
        URL = "zh"
        weight = 1

        [[languages.zh.menu.main]]
        name = "菜單"
        URL = "/"
        weight = 2


        [[languages.zh.menu.main]]
        name = "活動"
        URL = "event"
        weight = 3

        [[languages.zh.menu.main]]
        name = "交通資訊"
        URL = "traffic"
        weight = 4

        [[languages.zh.menu.main]]
        name = "QRcode 分享"
        URL = "contact"
        weight = 5
        
        [[languages.zh.menu.main]]
        name = "English"
        URL = "../en"
        weight = 6


        # footer
        [languages.zh.params.footer]
        title = ""
        content = ""
        # move 2 above value to coc section for better manage
        addressTitle = "地址"
        address = "新北市淡水區北新路117-2號"
        hoursTitle = "營業時間"
        hours = "中午12:30-晚上9:00  <br> 最後點餐晚上8:30"
        copyright = "Copyright &copy; 2024 黑客茶舖 "


############################## English config ###############################

    [languages.en]
        languageName = 'English'
        title="hacker's casa de cha"
        contentDir = "content/en"

############################## navigation en ###############################
        [[languages.en.menu.main]]
        name = "home"
        URL = "/"
        weight = 1

        [[languages.en.menu.main]]
        name = "menus"
        URL = "menus"
        weight = 2


        [[languages.en.menu.main]]
        name = "event"
        URL = "event"
        weight = 3

        [[languages.en.menu.main]]
        name = "Traffic info"
        URL = "traffic"
        weight = 4

        [[languages.en.menu.main]]
        name = "QR code"
        URL = "contact"
        weight = 5


        [[languages.en.menu.main]]
        name = "中文頁面"
        URL = "../zh"
        weight = 6

# subtitles
[languages.en.params.event]
heading="event"
heading2 ="menus"

        # footer
        [languages.en.params.footer]
        title = "about us"
        content = "hacker's casa de cha"
        address = "No. 117-2, Beixin Rd, Tamsui District"
        hours = "Monday–Friday: 12:30AM–9:00PM <br> Saturday & Sunday: 12:30AM–9:00PM"
        copyright = "Copyright &copy; 2022 hacker's casa de cha "

############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"



#################### default parameters ################################
[params]
# Meta data
description = "This is hacha.tw"
author = "Junyiza"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = false
expire_days = 2
        
# banner
[params.banner]

# banner
[params.logo]
image = "images/favicon.png"


# call to action
[params.call_to_action]
enable = true
title = "蛋糕預定"
picture = "images/traffic.png"
content = "送上一份甜蜜的禮物，讓您的最重要的人感受到愛和感激。我們為您準備了三款精美的蛋糕，口感綿密，香甜可口。每一口都是最真摯的祝福。現在下單，讓我們一起為您最重要的人送上最好的祝福！"
button_label = "馬上下單"
button_url = "https://junyi269333.typeform.com/to/ZHcRFfe9"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/hacha-landscape.png"


# footer
[params.footer]
title = "關於我們"
content = "茶文化與科技的交流站"
address = "新北市淡水區北新路117-2號"
hours = "Monday–Friday: 12:30AM–9:00PM <br> Saturday & Sunday: 12:30AM–9:00PM"
copyright = "Copyright &copy; 2022 黑客茶舖 "

############################# social site ########################
[params.social]

facebook = "https://www.facebook.com/profile.php?id=100064148673968"
twitter = "https://twitter.com/hacha_tw"
instagram = "https://www.instagram.com/hachatw/"
email = "hachataiwan@gmail.comgit "
line = "https://lin.ee/AE1OJ2k"
gmap = "https://goo.gl/maps/UTAV8zR9WPbgY9Xm6"

