######################## default configuration ####################

theme ="twenty-twenty-hugo"
defaultContentLanguage = 'zh'
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45

baseURL = "https://63fb671a83ec7f0008ab1c15--brilliant-syrniki-297892.netlify.app/" 


[languages]
############################## ZH config ###############################
    [languages.zh]
        languageName = '中文'
        title='黑客茶舖'
        contentDir = "content/zh"

############################## navigation zh ###############################
        [[languages.zh.menu.main]]
        name = "首頁"
        URL = "zh"
        weight = 1

        [[languages.zh.menu.main]]
        name = "菜單"
        URL = "menus"
        weight = 2

        [[languages.zh.menu.main]]
        name = "交通資訊"
        URL = "traffic"
        weight = 4

        [[languages.zh.menu.main]]
        name = "聯絡資訊"
        URL = "contact"
        weight = 5
        
        [[languages.zh.menu.main]]
        name = "English"
        URL = "../en"
        weight = 6

# subtitles
[languages.zh.params.event]
heading="活動"
heading2 ="店內菜單"

        # footer
        [languages.zh.params.footer]
        title = "關於我們"
        content = "黑客茶舖"
        address = "新北市淡水區北新路117-2號"
        hours = "Monday–Friday: 12:30AM–9:00PM <br> Saturday & Sunday: 12:30AM–9:00PM"
        copyright = "Copyright &copy; 2022 黑客茶舖 "


############################## English config ###############################

    [languages.en]
        languageName = 'English'
        title="hacker's casa de cha"
        contentDir = "content/en"

############################## navigation en ###############################
        [[languages.en.menu.main]]
        name = "home"
        URL = "/"
        weight = 1

        [[languages.en.menu.main]]
        name = "menus"
        URL = "menus"
        weight = 2

        [[languages.en.menu.main]]
        name = "Traffic info"
        URL = "traffic"
        weight = 4

        [[languages.en.menu.main]]
        name = "Contact"
        URL = "contact"
        weight = 5


        [[languages.en.menu.main]]
        name = "中文頁面"
        URL = "../zh"
        weight = 6

# subtitles
[languages.en.params.event]
heading="event"
heading2 ="menus"

        # footer
        [languages.en.params.footer]
        title = "about us"
        content = "hacker's casa de cha"
        address = "No. 117-2, Beixin Rd, Tamsui District"
        hours = "Monday–Friday: 12:30AM–9:00PM <br> Saturday & Sunday: 12:30AM–9:00PM"
        copyright = "Copyright &copy; 2022 hacker's casa de cha "

############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"



#################### default parameters ################################
[params]
# Meta data
description = "This is hacha.tw"
author = "Junyiza"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = false
expire_days = 2
        
# banner
[params.banner]

# banner
[params.logo]
image = "images/favicon.png"


# call to action
[params.call_to_action]
enable = true
title = "黑客茶舖臉書社團"
picture = "images/traffic.png"
content = "更多黑客茶舖相關活動，優惠，技術文章與討論，加入黑客茶舖臉書社團，獲得更多。"
button_label = "點此加入"
button_url = "https://www.facebook.com/groups/828300348362972"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/hacha-landscape.png"


# footer
[params.footer]
title = "關於我們"
content = "黑客茶舖"
address = "新北市淡水區北新路117-2號"
hours = "Monday–Friday: 12:30AM–9:00PM <br> Saturday & Sunday: 12:30AM–9:00PM"
copyright = "Copyright &copy; 2022 黑客茶舖 "

############################# social site ########################
[params.social]

facebook = "https://www.facebook.com/profile.php?id=100064148673968"
twitter = "https://twitter.com/hacha_tw"
instagram = "https://www.instagram.com/taiwan_hack_tea/"
line = "https://lin.ee/AE1OJ2k"
email = "hachataiwan@gmail.comgit "

