######################## default configuration ####################

theme ="twenty-twenty-hugo"
defaultContentLanguage = 'zh'

# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



[languages]
    [languages.en]
        baseURL = "https://hacha.tw/en" 
        languageName = 'English'
        languagedirection = "eng"
        title="hacker's casa de cha"
        contentDir = "content/en"

        [[languages.en.menu.main]]
        name = "home"
        URL = "/"
        weight = 1

        [[languages.en.menu.main]]
        name = "menus"
        URL = "menus"
        weight = 2

        [[languages.en.menu.main]]
        name = "Traffic info"
        URL = "traffic"
        weight = 4

        [[languages.en.menu.main]]
        name = "Contact"
        URL = "contact"
        weight = 5

    [languages.zh]
        baseURL = "https://hacha.tw/zh"
        languageName = '中文'
        languagedirection = "zhu"
        title='黑客茶舖'
        contentDir = "content/zh"

        [[languages.zh.menu.main]]
        name = "首頁"
        URL = "/"
        weight = 1

        [[languages.zh.menu.main]]
        name = "菜單"
        URL = "menus"
        weight = 2

        [[languages.zh.menu.main]]
        name = "交通資訊"
        URL = "traffic"
        weight = 4

        [[languages.zh.menu.main]]
        name = "聯絡資訊"
        URL = "contact"
        weight = 5
        
############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################


#################### default parameters ################################
[params]
# Meta data
description = "This is meta description"
author = "Themefisher"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = false
expire_days = 2
        
# banner
[params.banner]


# banner
[params.logo]
image = "images/favicon.png"

# blog
[params.blog]
heading="餐點 Meals"
heading2 ="飲品 Drinks"

# call to action
[params.call_to_action]
enable = false
title = "Contact us for more information."
picture = "images/traffic.png"
content = "https://g.page/Thtea?share Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/hacha-landscape.png"


# footer
[params.footer]
title = "關於我們"
content = "黑客茶舖"
address = "新北市淡水區北新路117-2號"
hours = "Monday–Friday: 12:30AM–9:00PM <br> Saturday & Sunday: 12:30AM–9:00PM"
copyright = "Copyright &copy; 2022 黑客茶舖 "

############################# social site ########################
[params.social]

facebook = "https://www.facebook.com/"
twitter = "#"
instagram = "#"
email = "@gmail.com"

