[en]
    title="hacha"
    languageName = "English"
    weight=2
    languagedir = "ltr"
    contentdir = "content/en"
[zh]
    title = "黑客茶舖"
    languageName = "繁體中文"
    weight = 1
    languagedir = "ltr"
    contentdir = "content/zh"